spring:
  datasource:
   url : jdbc:mysql://localhost:3306/resume
   username : root
   password : 123
   driverClassName : com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml


logging:
  level:
#    org.springframework.boot: debug
    mybatis: debug
    com.loop.resume.dao: debug
    com.loop.resume.resume: debug
server:
  tomcat:
    max-http-header-size: 102400
  port: 8088

